// Generated by scripts/build-plugin.mjs. Do not edit.


// src/compaction/curator.ts
import { createRequire as createRequire2 } from "node:module";
import { homedir } from "node:os";
import { join as join2, resolve } from "node:path";
import { pathToFileURL } from "node:url";

// ../tavern-store/src/store.ts
import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import * as path from "node:path";

// ../tavern-format/lib/png.js
var PNG_SIGNATURE = Uint8Array.from([137, 80, 78, 71, 13, 10, 26, 10]);
var PngFormatError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "PngFormatError";
  }
};
var CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 3988292384 ^ c >>> 1 : c >>> 1;
    }
    table[n] = c >>> 0;
  }
  return table;
})();
function crc32(...buffers) {
  let crc2 = 4294967295;
  for (const buf of buffers) {
    for (let i = 0; i < buf.length; i++) {
      crc2 = CRC_TABLE[(crc2 ^ buf[i]) >>> 0 & 255] ^ crc2 >>> 8;
    }
  }
  return (crc2 ^ 4294967295) >>> 0;
}
function isPng(buf) {
  if (buf.length < PNG_SIGNATURE.length)
    return false;
  for (let i = 0; i < PNG_SIGNATURE.length; i++) {
    if (buf[i] !== PNG_SIGNATURE[i])
      return false;
  }
  return true;
}
function parsePngChunks(buf) {
  if (!isPng(buf))
    throw new PngFormatError("not a PNG file (bad signature)");
  const chunks = [];
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  let offset = PNG_SIGNATURE.length;
  while (offset + 8 <= buf.length) {
    const length = view.getUint32(offset);
    const typeBytes = buf.subarray(offset + 4, offset + 8);
    const type = String.fromCharCode(...typeBytes);
    const dataStart = offset + 8;
    const dataEnd = dataStart + length;
    if (dataEnd + 4 > buf.length) {
      throw new PngFormatError(`chunk '${type}' at ${offset} overruns file end`);
    }
    chunks.push({ type, data: buf.subarray(dataStart, dataEnd), offset });
    const storedCrc = view.getUint32(dataEnd);
    const actualCrc = crc32(typeBytes, buf.subarray(dataStart, dataEnd));
    if (storedCrc !== actualCrc) {
      throw new PngFormatError(`chunk '${type}' at ${offset} has bad CRC (stored ${storedCrc.toString(16)}, actual ${actualCrc.toString(16)})`);
    }
    offset = dataEnd + 4;
    if (type === "IEND")
      break;
  }
  const last = chunks[chunks.length - 1];
  if (!last || last.type !== "IEND")
    throw new PngFormatError("missing IEND chunk");
  return chunks;
}
function readTextChunks(buf) {
  const out = [];
  for (const chunk of parsePngChunks(buf)) {
    if (chunk.type !== "tEXt")
      continue;
    const nul = chunk.data.indexOf(0);
    if (nul < 0)
      continue;
    const keyword = latin1Decode(chunk.data.subarray(0, nul));
    const text = latin1Decode(chunk.data.subarray(nul + 1));
    out.push({ keyword, text });
  }
  return out;
}
function latin1Decode(bytes) {
  let out = "";
  for (let i = 0; i < bytes.length; i++)
    out += String.fromCharCode(bytes[i]);
  return out;
}
function latin1Encode(text) {
  const out = new Uint8Array(text.length);
  for (let i = 0; i < text.length; i++)
    out[i] = text.charCodeAt(i) & 255;
  return out;
}
function u32be(value) {
  return new Uint8Array([value >>> 24 & 255, value >>> 16 & 255, value >>> 8 & 255, value & 255]);
}
function encodeChunk(type, data) {
  const typeBytes = latin1Encode(type);
  const crc2 = crc32(typeBytes, data);
  const out = new Uint8Array(12 + data.length);
  out.set(u32be(data.length), 0);
  out.set(typeBytes, 4);
  out.set(data, 8);
  out.set(u32be(crc2), 8 + data.length);
  return out;
}
function encodeTextChunk(keyword, text) {
  const data = new Uint8Array(keyword.length + 1 + text.length);
  data.set(latin1Encode(keyword), 0);
  data[keyword.length] = 0;
  data.set(latin1Encode(text), keyword.length + 1);
  return encodeChunk("tEXt", data);
}
function concat(...parts) {
  const total = parts.reduce((n, p) => n + p.length, 0);
  const out = new Uint8Array(total);
  let at = 0;
  for (const p of parts) {
    out.set(p, at);
    at += p.length;
  }
  return out;
}
function writeTextChunks(png, entries) {
  const chunks = parsePngChunks(png);
  const parts = [PNG_SIGNATURE];
  const pending = new Map(entries.map((e) => [e.keyword, e]));
  for (const chunk of chunks) {
    let bytes;
    if (chunk.type === "tEXt") {
      const nul = chunk.data.indexOf(0);
      const keyword = nul >= 0 ? latin1Decode(chunk.data.subarray(0, nul)) : "";
      const replacement = pending.get(keyword);
      if (replacement) {
        pending.delete(keyword);
        bytes = encodeTextChunk(replacement.keyword, replacement.text);
      } else {
        bytes = sliceChunkBytes(png, chunk);
      }
    } else if (chunk.type === "IEND") {
      for (const e of pending.values())
        parts.push(encodeTextChunk(e.keyword, e.text));
      pending.clear();
      bytes = sliceChunkBytes(png, chunk);
    } else {
      bytes = sliceChunkBytes(png, chunk);
    }
    parts.push(bytes);
  }
  return concat(...parts);
}
function sliceChunkBytes(png, chunk) {
  return png.subarray(chunk.offset, chunk.offset + 12 + chunk.data.length);
}
var CARD_CHUNK_V2 = "chara";
var CARD_CHUNK_V3 = "ccv3";
function extractCardJson(png) {
  const texts = readTextChunks(png);
  const found = texts.find((t) => t.keyword === CARD_CHUNK_V3) ?? texts.find((t) => t.keyword === CARD_CHUNK_V2);
  if (!found || !found.text)
    return null;
  return base64ToUtf8(found.text);
}
function base64ToUtf8(base64) {
  return Buffer.from(base64, "base64").toString("utf8");
}
function utf8ToBase64(text) {
  return Buffer.from(text, "utf8").toString("base64");
}

// ../tavern-format/lib/card.js
var CardFormatError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "CardFormatError";
  }
};
function decodeCharacterCard(input) {
  let obj;
  if (input instanceof Uint8Array || input instanceof ArrayBuffer) {
    const bytes = input instanceof ArrayBuffer ? new Uint8Array(input) : input;
    if (!isPng(bytes))
      throw new CardFormatError("binary input is not a PNG file");
    const json = extractCardJson(bytes);
    if (json === null)
      throw new CardFormatError("PNG has no chara/ccv3 tEXt chunk");
    obj = parseJson(json);
  } else {
    obj = input;
  }
  if (typeof obj !== "object" || obj === null || Array.isArray(obj)) {
    throw new CardFormatError("card root is not an object");
  }
  return fromCardObject(obj);
}
function parseJson(text) {
  try {
    return JSON.parse(text);
  } catch (cause) {
    throw new CardFormatError(`card chunk JSON is invalid: ${String(cause)}`);
  }
}
function fromCardObject(root) {
  const spec = typeof root["spec"] === "string" ? root["spec"] : void 0;
  let data;
  let specName;
  let specVersion;
  if (spec === "chara_card_v2" || spec === "chara_card_v3") {
    const raw = root["data"];
    if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
      throw new CardFormatError(`spec ${spec} present but 'data' is not an object`);
    }
    data = raw;
    specName = spec;
    specVersion = typeof root["spec_version"] === "string" ? root["spec_version"] : spec === "chara_card_v3" ? "3.0" : "2.0";
  } else if (spec !== void 0) {
    data = root["data"] ?? {};
    specName = "chara_card_v3";
    specVersion = typeof root["spec_version"] === "string" ? root["spec_version"] : "3.0";
  } else {
    data = root;
    specName = "chara_card_v2";
    specVersion = "1.0";
  }
  if (typeof data["name"] !== "string" || data["name"].length === 0) {
    throw new CardFormatError("card data has no 'name' string");
  }
  return {
    spec: specName,
    specVersion,
    data: toCardDataIR(data),
    // ST 导出的真实卡顶层并存 V1 兼容字段与 spec/data 三层——raw 必须存整个对象
    raw: structuredClone(root)
  };
}
function str(value, fallback = "") {
  return typeof value === "string" ? value : fallback;
}
function strArray(value) {
  return Array.isArray(value) ? value.filter((v) => typeof v === "string") : [];
}
function toCardDataIR(data) {
  const book = data["character_book"];
  const ir = {
    name: str(data["name"]),
    description: str(data["description"]),
    personality: str(data["personality"]),
    scenario: str(data["scenario"]),
    firstMes: str(data["first_mes"]),
    mesExample: str(data["mes_example"]),
    creatorNotes: str(data["creator_notes"]),
    systemPrompt: str(data["system_prompt"]),
    postHistoryInstructions: str(data["post_history_instructions"]),
    alternateGreetings: strArray(data["alternate_greetings"]),
    tags: strArray(data["tags"]),
    creator: str(data["creator"]),
    characterVersion: str(data["character_version"]),
    extensions: typeof data["extensions"] === "object" && data["extensions"] !== null ? data["extensions"] : {}
  };
  if (isCharacterBook(book))
    ir.characterBook = book;
  if (Array.isArray(data["assets"]))
    ir.assets = data["assets"].filter((a) => typeof a === "object" && a !== null);
  if (typeof data["nickname"] === "string")
    ir.nickname = data["nickname"];
  if (isStringRecord(data["creator_notes_multilingual"]))
    ir.creatorNotesMultilingual = data["creator_notes_multilingual"];
  if (strArray(data["source"]).length > 0)
    ir.source = strArray(data["source"]);
  if (Array.isArray(data["group_only_greetings"]))
    ir.groupOnlyGreetings = strArray(data["group_only_greetings"]);
  if (typeof data["creation_date"] === "number")
    ir.creationDate = data["creation_date"];
  if (typeof data["modification_date"] === "number")
    ir.modificationDate = data["modification_date"];
  return ir;
}
function isCharacterBook(value) {
  return typeof value === "object" && value !== null && Array.isArray(value.entries);
}
function isStringRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function cardDataToRaw(ir) {
  const rawBase = typeof ir.raw["data"] === "object" && ir.raw["data"] !== null ? structuredClone(ir.raw["data"]) : {};
  const data = { ...rawBase };
  const d = ir.data;
  data["name"] = d.name;
  data["description"] = d.description;
  data["personality"] = d.personality;
  data["scenario"] = d.scenario;
  data["first_mes"] = d.firstMes;
  data["mes_example"] = d.mesExample;
  data["creator_notes"] = d.creatorNotes;
  data["system_prompt"] = d.systemPrompt;
  data["post_history_instructions"] = d.postHistoryInstructions;
  data["alternate_greetings"] = d.alternateGreetings;
  data["tags"] = d.tags;
  data["creator"] = d.creator;
  data["character_version"] = d.characterVersion;
  data["extensions"] = d.extensions;
  if (d.characterBook === void 0)
    delete data["character_book"];
  else
    data["character_book"] = d.characterBook;
  for (const [irKey, jsonKey] of V3_FIELDS) {
    const value = d[irKey];
    if (value === void 0)
      delete data[jsonKey];
    else
      data[jsonKey] = value;
  }
  return data;
}
var V3_FIELDS = [
  ["assets", "assets"],
  ["nickname", "nickname"],
  ["creatorNotesMultilingual", "creator_notes_multilingual"],
  ["source", "source"],
  ["groupOnlyGreetings", "group_only_greetings"],
  ["creationDate", "creation_date"],
  ["modificationDate", "modification_date"]
];
function encodeCharacterCardJson(ir) {
  return {
    ...structuredClone(ir.raw),
    spec: ir.spec,
    spec_version: ir.specVersion,
    data: cardDataToRaw(ir)
  };
}
function encodeCharacterCardPng(ir, template) {
  const entries = [
    { keyword: CARD_CHUNK_V2, text: utf8ToBase64(JSON.stringify(toV2Json(ir))) }
  ];
  if (ir.spec === "chara_card_v3") {
    entries.push({ keyword: CARD_CHUNK_V3, text: utf8ToBase64(JSON.stringify(encodeCharacterCardJson(ir))) });
  }
  return writeTextChunks(template, entries);
}
function toV2Json(ir) {
  const data = cardDataToRaw(ir);
  for (const jsonKey of V3_FIELDS.map((f) => f[1]))
    delete data[jsonKey];
  return {
    ...structuredClone(ir.raw),
    name: ir.data.name,
    description: ir.data.description,
    personality: ir.data.personality,
    scenario: ir.data.scenario,
    first_mes: ir.data.firstMes,
    mes_example: ir.data.mesExample,
    tags: ir.data.tags,
    spec: "chara_card_v2",
    spec_version: "2.0",
    data
  };
}

// ../tavern-format/lib/worldbook.js
var WorldBookFormatError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "WorldBookFormatError";
  }
};
function parseWorldInfoFile(name2, obj) {
  const rawEntries = obj["entries"];
  if (typeof rawEntries !== "object" || rawEntries === null || Array.isArray(rawEntries)) {
    throw new WorldBookFormatError("world info file has no 'entries' object");
  }
  const entries = [];
  for (const value of Object.values(rawEntries)) {
    if (typeof value !== "object" || value === null)
      continue;
    entries.push(normalizeEntry(value));
  }
  entries.sort((a, b) => a.uid - b.uid);
  const { ["entries"]: _dropped, ...extra } = obj;
  return { name: name2, entries, extra: Object.keys(extra).length > 0 ? extra : void 0 };
}
function serializeWorldInfoFile(ir) {
  const entries = {};
  for (const entry of [...ir.entries].sort((a, b) => a.uid - b.uid)) {
    entries[String(entry.uid)] = entryToFileObject(entry);
  }
  return { ...ir.extra ?? {}, entries };
}
var KNOWN_FIELDS = /* @__PURE__ */ new Set([
  "uid",
  "key",
  "keysecondary",
  "comment",
  "content",
  "constant",
  "vectorized",
  "selective",
  "selectiveLogic",
  "addMemo",
  "order",
  "position",
  "disable",
  "ignoreBudget",
  "excludeRecursion",
  "preventRecursion",
  "delayUntilRecursion",
  "probability",
  "useProbability",
  "depth",
  "outletName",
  "group",
  "groupOverride",
  "groupWeight",
  "scanDepth",
  "caseSensitive",
  "matchWholeWords",
  "useGroupScoring",
  "automationId",
  "role",
  "sticky",
  "cooldown",
  "delay",
  "triggers",
  "matchPersonaDescription",
  "matchCharacterDescription",
  "matchCharacterPersonality",
  "matchCharacterDepthPrompt",
  "matchScenario",
  "matchCreatorNotes",
  "extra"
]);
function normalizeEntry(raw) {
  const extra = {};
  for (const [k, v] of Object.entries(raw)) {
    if (!KNOWN_FIELDS.has(k))
      extra[k] = v;
  }
  return {
    uid: num(raw["uid"], 0),
    key: strArray2(raw["key"]),
    keysecondary: strArray2(raw["keysecondary"]),
    comment: str2(raw["comment"]),
    content: str2(raw["content"]),
    constant: bool(raw["constant"], false),
    vectorized: bool(raw["vectorized"], false),
    selective: bool(raw["selective"], true),
    selectiveLogic: num(raw["selectiveLogic"], 0),
    addMemo: bool(raw["addMemo"], false),
    order: num(raw["order"], 100),
    position: num(raw["position"], 0),
    disable: bool(raw["disable"], false),
    ignoreBudget: bool(raw["ignoreBudget"], false),
    excludeRecursion: bool(raw["excludeRecursion"], false),
    preventRecursion: bool(raw["preventRecursion"], false),
    delayUntilRecursion: num(raw["delayUntilRecursion"], 0),
    probability: num(raw["probability"], 100),
    useProbability: bool(raw["useProbability"], true),
    depth: num(raw["depth"], 4),
    outletName: str2(raw["outletName"]),
    group: str2(raw["group"]),
    groupOverride: bool(raw["groupOverride"], false),
    groupWeight: num(raw["groupWeight"], 100),
    scanDepth: nullableNum(raw["scanDepth"]),
    caseSensitive: nullableBool(raw["caseSensitive"]),
    matchWholeWords: nullableBool(raw["matchWholeWords"]),
    useGroupScoring: nullableBool(raw["useGroupScoring"]),
    automationId: str2(raw["automationId"]),
    role: num(raw["role"], 0),
    sticky: nullableNum(raw["sticky"]),
    cooldown: nullableNum(raw["cooldown"]),
    delay: nullableNum(raw["delay"]),
    triggers: strArray2(raw["triggers"]),
    matchPersonaDescription: bool(raw["matchPersonaDescription"], false),
    matchCharacterDescription: bool(raw["matchCharacterDescription"], false),
    matchCharacterPersonality: bool(raw["matchCharacterPersonality"], false),
    matchCharacterDepthPrompt: bool(raw["matchCharacterDepthPrompt"], false),
    matchScenario: bool(raw["matchScenario"], false),
    matchCreatorNotes: bool(raw["matchCreatorNotes"], false),
    extra: Object.keys(extra).length > 0 ? extra : void 0
  };
}
function entryToFileObject(entry) {
  const { extra, ...fields } = entry;
  return { ...fields, ...extra ?? {} };
}
function parseCharacterBook(book) {
  const entries = (book.entries ?? []).map((raw, index) => bookEntryToLoreEntry(raw, index));
  return { name: book.name ?? "", entries };
}
function bookEntryToLoreEntry(raw, index) {
  const ext = raw.extensions ?? {};
  const uid = numOr(raw.id, ext["uid"], index);
  const entry = normalizeEntry({
    uid,
    key: raw.keys ?? [],
    keysecondary: raw.secondary_keys ?? [],
    comment: raw.comment ?? raw.name ?? "",
    content: raw.content ?? "",
    constant: boolOr(raw.constant, ext["constant"], false),
    disable: raw.enabled === false,
    order: numOr(ext["order"], raw.insertion_order, 100),
    position: bookPositionToSt(raw.position, ext["position"]),
    selective: boolOr(raw.selective, ext["selective"], true),
    selectiveLogic: num(ext["selectiveLogic"], 0),
    caseSensitive: nullableBoolOr(raw.case_sensitive, ext["case_sensitive"]),
    probability: numOr(ext["probability"], 100, 100),
    useProbability: boolOr(ext["useProbability"], true, true),
    depth: numOr(ext["depth"], 4, 4),
    group: str2(ext["group"]),
    groupOverride: bool(ext["group_override"], false),
    groupWeight: numOr(ext["group_weight"], 100, 100),
    excludeRecursion: boolOr(ext["exclude_recursion"], false, false),
    preventRecursion: boolOr(ext["prevent_recursion"], false, false),
    delayUntilRecursion: numOr(ext["delay_until_recursion"], 0, 0),
    scanDepth: nullableNum(ext["scan_depth"]),
    matchWholeWords: nullableBool(ext["match_whole_words"]),
    useGroupScoring: nullableBool(ext["use_group_scoring"]),
    role: num(ext["role"], 0),
    vectorized: bool(ext["vectorized"], false),
    sticky: nullableNum(ext["sticky"]),
    cooldown: nullableNum(ext["cooldown"]),
    delay: nullableNum(ext["delay"]),
    triggers: strArray2(ext["triggers"])
  });
  const carried = {};
  if (raw.priority !== void 0)
    carried["book.priority"] = raw.priority;
  if (raw.use_regex !== void 0)
    carried["book.use_regex"] = raw.use_regex;
  if (raw.name !== void 0)
    carried["book.name"] = raw.name;
  if (Object.keys(carried).length > 0)
    entry.extra = { ...entry.extra ?? {}, ...carried };
  return entry;
}
function bookPositionToSt(bookPos, extPos) {
  if (typeof extPos === "number")
    return extPos;
  if (bookPos === "after_char")
    return 1;
  return 0;
}
function str2(v) {
  return typeof v === "string" ? v : "";
}
function num(v, fallback) {
  return typeof v === "number" && Number.isFinite(v) ? v : fallback;
}
function numOr(v, v2, fallback) {
  return typeof v === "number" && Number.isFinite(v) ? v : num(v2, fallback);
}
function nullableNum(v) {
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}
function bool(v, fallback) {
  return typeof v === "boolean" ? v : fallback;
}
function boolOr(v, v2, fallback) {
  return typeof v === "boolean" ? v : bool(v2, fallback);
}
function nullableBool(v) {
  return typeof v === "boolean" ? v : null;
}
function nullableBoolOr(v, v2) {
  return typeof v === "boolean" ? v : nullableBool(v2);
}
function strArray2(v) {
  return Array.isArray(v) ? v.filter((x) => typeof x === "string") : [];
}

// ../tavern-format/lib/chat.js
var ChatFormatError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "ChatFormatError";
  }
};
function parseChatLog(text) {
  const lines = text.split("\n");
  let header;
  const messages = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.length === 0)
      continue;
    let obj;
    try {
      obj = JSON.parse(line);
    } catch (cause) {
      throw new ChatFormatError(`line ${i + 1} is not valid JSON: ${String(cause)}`);
    }
    if (typeof obj !== "object" || obj === null)
      throw new ChatFormatError(`line ${i + 1} is not an object`);
    if (header === void 0)
      header = obj;
    else
      messages.push(obj);
  }
  if (header === void 0)
    throw new ChatFormatError("chat log is empty");
  return { header, messages };
}
function serializeChatLog(ir) {
  const lines = [JSON.stringify(ir.header), ...ir.messages.map((m) => JSON.stringify(m))];
  return lines.join("\n") + "\n";
}

// ../../node_modules/.pnpm/fflate@0.8.3/node_modules/fflate/esm/index.mjs
import { createRequire } from "module";
var require2 = createRequire("/");
var _a;
var Worker;
var isMarkedAsUntransferable;
try {
  _a = require2("worker_threads"), Worker = _a.Worker, isMarkedAsUntransferable = _a.isMarkedAsUntransferable;
} catch (e) {
}
var u8 = Uint8Array;
var u16 = Uint16Array;
var i32 = Int32Array;
var fleb = new u8([
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  4,
  4,
  4,
  4,
  5,
  5,
  5,
  5,
  0,
  /* unused */
  0,
  0,
  /* impossible */
  0
]);
var fdeb = new u8([
  0,
  0,
  0,
  0,
  1,
  1,
  2,
  2,
  3,
  3,
  4,
  4,
  5,
  5,
  6,
  6,
  7,
  7,
  8,
  8,
  9,
  9,
  10,
  10,
  11,
  11,
  12,
  12,
  13,
  13,
  /* unused */
  0,
  0
]);
var clim = new u8([16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15]);
var freb = function(eb, start) {
  var b = new u16(31);
  for (var i = 0; i < 31; ++i) {
    b[i] = start += 1 << eb[i - 1];
  }
  var r = new i32(b[30]);
  for (var i = 1; i < 30; ++i) {
    for (var j = b[i]; j < b[i + 1]; ++j) {
      r[j] = j - b[i] << 5 | i;
    }
  }
  return { b, r };
};
var _a = freb(fleb, 2);
var fl = _a.b;
var revfl = _a.r;
fl[28] = 258, revfl[258] = 28;
var _b = freb(fdeb, 0);
var fd = _b.b;
var revfd = _b.r;
var rev = new u16(32768);
for (i = 0; i < 32768; ++i) {
  x = (i & 43690) >> 1 | (i & 21845) << 1;
  x = (x & 52428) >> 2 | (x & 13107) << 2;
  x = (x & 61680) >> 4 | (x & 3855) << 4;
  rev[i] = ((x & 65280) >> 8 | (x & 255) << 8) >> 1;
}
var x;
var i;
var hMap = function(cd, mb, r) {
  var s = cd.length;
  var i = 0;
  var l = new u16(mb);
  for (; i < s; ++i) {
    if (cd[i])
      ++l[cd[i] - 1];
  }
  var le = new u16(mb);
  for (i = 1; i < mb; ++i) {
    le[i] = le[i - 1] + l[i - 1] << 1;
  }
  var co;
  if (r) {
    co = new u16(1 << mb);
    var rvb = 15 - mb;
    for (i = 0; i < s; ++i) {
      if (cd[i]) {
        var sv = i << 4 | cd[i];
        var r_1 = mb - cd[i];
        var v = le[cd[i] - 1]++ << r_1;
        for (var m = v | (1 << r_1) - 1; v <= m; ++v) {
          co[rev[v] >> rvb] = sv;
        }
      }
    }
  } else {
    co = new u16(s);
    for (i = 0; i < s; ++i) {
      if (cd[i]) {
        co[i] = rev[le[cd[i] - 1]++] >> 15 - cd[i];
      }
    }
  }
  return co;
};
var flt = new u8(288);
for (i = 0; i < 144; ++i)
  flt[i] = 8;
var i;
for (i = 144; i < 256; ++i)
  flt[i] = 9;
var i;
for (i = 256; i < 280; ++i)
  flt[i] = 7;
var i;
for (i = 280; i < 288; ++i)
  flt[i] = 8;
var i;
var fdt = new u8(32);
for (i = 0; i < 32; ++i)
  fdt[i] = 5;
var i;
var flm = /* @__PURE__ */ hMap(flt, 9, 0);
var flrm = /* @__PURE__ */ hMap(flt, 9, 1);
var fdm = /* @__PURE__ */ hMap(fdt, 5, 0);
var fdrm = /* @__PURE__ */ hMap(fdt, 5, 1);
var max = function(a) {
  var m = a[0];
  for (var i = 1; i < a.length; ++i) {
    if (a[i] > m)
      m = a[i];
  }
  return m;
};
var bits = function(d, p, m) {
  var o = p / 8 | 0;
  return (d[o] | d[o + 1] << 8) >> (p & 7) & m;
};
var bits16 = function(d, p) {
  var o = p / 8 | 0;
  return (d[o] | d[o + 1] << 8 | d[o + 2] << 16) >> (p & 7);
};
var shft = function(p) {
  return (p + 7) / 8 | 0;
};
var slc = function(v, s, e) {
  if (s == null || s < 0)
    s = 0;
  if (e == null || e > v.length)
    e = v.length;
  return new u8(v.subarray(s, e));
};
var ec = [
  "unexpected EOF",
  "invalid block type",
  "invalid length/literal",
  "invalid distance",
  "stream finished",
  "no stream handler",
  ,
  // determined by compression function
  "no callback",
  "invalid UTF-8 data",
  "extra field too long",
  "date not in range 1980-2099",
  "filename too long",
  "stream finishing",
  "invalid zip data"
  // determined by unknown compression method
];
var err = function(ind, msg, nt) {
  var e = new Error(msg || ec[ind]);
  e.code = ind;
  if (Error.captureStackTrace)
    Error.captureStackTrace(e, err);
  if (!nt)
    throw e;
  return e;
};
var inflt = function(dat, st, buf, dict) {
  var sl = dat.length, dl = dict ? dict.length : 0;
  if (!sl || st.f && !st.l)
    return buf || new u8(0);
  var noBuf = !buf;
  var resize = noBuf || st.i != 2;
  var noSt = st.i;
  if (noBuf)
    buf = new u8(sl * 3);
  var cbuf = function(l2) {
    var bl = buf.length;
    if (l2 > bl) {
      var nbuf = new u8(Math.max(bl * 2, l2));
      nbuf.set(buf);
      buf = nbuf;
    }
  };
  var final = st.f || 0, pos = st.p || 0, bt = st.b || 0, lm = st.l, dm = st.d, lbt = st.m, dbt = st.n;
  var tbts = sl * 8;
  do {
    if (!lm) {
      final = bits(dat, pos, 1);
      var type = bits(dat, pos + 1, 3);
      pos += 3;
      if (!type) {
        var s = shft(pos) + 4, l = dat[s - 4] | dat[s - 3] << 8, t = s + l;
        if (t > sl) {
          if (noSt)
            err(0);
          break;
        }
        if (resize)
          cbuf(bt + l);
        buf.set(dat.subarray(s, t), bt);
        st.b = bt += l, st.p = pos = t * 8, st.f = final;
        continue;
      } else if (type == 1)
        lm = flrm, dm = fdrm, lbt = 9, dbt = 5;
      else if (type == 2) {
        var hLit = bits(dat, pos, 31) + 257, hcLen = bits(dat, pos + 10, 15) + 4;
        var tl = hLit + bits(dat, pos + 5, 31) + 1;
        pos += 14;
        var ldt = new u8(tl);
        var clt = new u8(19);
        for (var i = 0; i < hcLen; ++i) {
          clt[clim[i]] = bits(dat, pos + i * 3, 7);
        }
        pos += hcLen * 3;
        var clb = max(clt), clbmsk = (1 << clb) - 1;
        var clm = hMap(clt, clb, 1);
        for (var i = 0; i < tl; ) {
          var r = clm[bits(dat, pos, clbmsk)];
          pos += r & 15;
          var s = r >> 4;
          if (s < 16) {
            ldt[i++] = s;
          } else {
            var c = 0, n = 0;
            if (s == 16)
              n = 3 + bits(dat, pos, 3), pos += 2, c = ldt[i - 1];
            else if (s == 17)
              n = 3 + bits(dat, pos, 7), pos += 3;
            else if (s == 18)
              n = 11 + bits(dat, pos, 127), pos += 7;
            while (n--)
              ldt[i++] = c;
          }
        }
        var lt = ldt.subarray(0, hLit), dt = ldt.subarray(hLit);
        lbt = max(lt);
        dbt = max(dt);
        lm = hMap(lt, lbt, 1);
        dm = hMap(dt, dbt, 1);
      } else
        err(1);
      if (pos > tbts) {
        if (noSt)
          err(0);
        break;
      }
    }
    if (resize)
      cbuf(bt + 131072);
    var lms = (1 << lbt) - 1, dms = (1 << dbt) - 1;
    var lpos = pos;
    for (; ; lpos = pos) {
      var c = lm[bits16(dat, pos) & lms], sym = c >> 4;
      pos += c & 15;
      if (pos > tbts) {
        if (noSt)
          err(0);
        break;
      }
      if (!c)
        err(2);
      if (sym < 256)
        buf[bt++] = sym;
      else if (sym == 256) {
        lpos = pos, lm = null;
        break;
      } else {
        var add = sym - 254;
        if (sym > 264) {
          var i = sym - 257, b = fleb[i];
          add = bits(dat, pos, (1 << b) - 1) + fl[i];
          pos += b;
        }
        var d = dm[bits16(dat, pos) & dms], dsym = d >> 4;
        if (!d)
          err(3);
        pos += d & 15;
        var dt = fd[dsym];
        if (dsym > 3) {
          var b = fdeb[dsym];
          dt += bits16(dat, pos) & (1 << b) - 1, pos += b;
        }
        if (pos > tbts) {
          if (noSt)
            err(0);
          break;
        }
        if (resize)
          cbuf(bt + 131072);
        var end = bt + add;
        if (bt < dt) {
          var shift = dl - dt, dend = Math.min(dt, end);
          if (shift + bt < 0)
            err(3);
          for (; bt < dend; ++bt)
            buf[bt] = dict[shift + bt];
        }
        for (; bt < end; ++bt)
          buf[bt] = buf[bt - dt];
      }
    }
    st.l = lm, st.p = lpos, st.b = bt, st.f = final;
    if (lm)
      final = 1, st.m = lbt, st.d = dm, st.n = dbt;
  } while (!final);
  return bt != buf.length && noBuf ? slc(buf, 0, bt) : buf.subarray(0, bt);
};
var wbits = function(d, p, v) {
  v <<= p & 7;
  var o = p / 8 | 0;
  d[o] |= v;
  d[o + 1] |= v >> 8;
};
var wbits16 = function(d, p, v) {
  v <<= p & 7;
  var o = p / 8 | 0;
  d[o] |= v;
  d[o + 1] |= v >> 8;
  d[o + 2] |= v >> 16;
};
var hTree = function(d, mb) {
  var t = [];
  for (var i = 0; i < d.length; ++i) {
    if (d[i])
      t.push({ s: i, f: d[i] });
  }
  var s = t.length;
  var t2 = t.slice();
  if (!s)
    return { t: et, l: 0 };
  if (s == 1) {
    var v = new u8(t[0].s + 1);
    v[t[0].s] = 1;
    return { t: v, l: 1 };
  }
  t.sort(function(a, b) {
    return a.f - b.f;
  });
  t.push({ s: -1, f: 25001 });
  var l = t[0], r = t[1], i0 = 0, i1 = 1, i2 = 2;
  t[0] = { s: -1, f: l.f + r.f, l, r };
  while (i1 != s - 1) {
    l = t[t[i0].f < t[i2].f ? i0++ : i2++];
    r = t[i0 != i1 && t[i0].f < t[i2].f ? i0++ : i2++];
    t[i1++] = { s: -1, f: l.f + r.f, l, r };
  }
  var maxSym = t2[0].s;
  for (var i = 1; i < s; ++i) {
    if (t2[i].s > maxSym)
      maxSym = t2[i].s;
  }
  var tr = new u16(maxSym + 1);
  var mbt = ln(t[i1 - 1], tr, 0);
  if (mbt > mb) {
    var i = 0, dt = 0;
    var lft = mbt - mb, cst = 1 << lft;
    t2.sort(function(a, b) {
      return tr[b.s] - tr[a.s] || a.f - b.f;
    });
    for (; i < s; ++i) {
      var i2_1 = t2[i].s;
      if (tr[i2_1] > mb) {
        dt += cst - (1 << mbt - tr[i2_1]);
        tr[i2_1] = mb;
      } else
        break;
    }
    dt >>= lft;
    while (dt > 0) {
      var i2_2 = t2[i].s;
      if (tr[i2_2] < mb)
        dt -= 1 << mb - tr[i2_2]++ - 1;
      else
        ++i;
    }
    for (; i >= 0 && dt; --i) {
      var i2_3 = t2[i].s;
      if (tr[i2_3] == mb) {
        --tr[i2_3];
        ++dt;
      }
    }
    mbt = mb;
  }
  return { t: new u8(tr), l: mbt };
};
var ln = function(n, l, d) {
  return n.s == -1 ? Math.max(ln(n.l, l, d + 1), ln(n.r, l, d + 1)) : l[n.s] = d;
};
var lc = function(c) {
  var s = c.length;
  while (s && !c[--s])
    ;
  var cl = new u16(++s);
  var cli = 0, cln = c[0], cls = 1;
  var w = function(v) {
    cl[cli++] = v;
  };
  for (var i = 1; i <= s; ++i) {
    if (c[i] == cln && i != s)
      ++cls;
    else {
      if (!cln && cls > 2) {
        for (; cls > 138; cls -= 138)
          w(32754);
        if (cls > 2) {
          w(cls > 10 ? cls - 11 << 5 | 28690 : cls - 3 << 5 | 12305);
          cls = 0;
        }
      } else if (cls > 3) {
        w(cln), --cls;
        for (; cls > 6; cls -= 6)
          w(8304);
        if (cls > 2)
          w(cls - 3 << 5 | 8208), cls = 0;
      }
      while (cls--)
        w(cln);
      cls = 1;
      cln = c[i];
    }
  }
  return { c: cl.subarray(0, cli), n: s };
};
var clen = function(cf, cl) {
  var l = 0;
  for (var i = 0; i < cl.length; ++i)
    l += cf[i] * cl[i];
  return l;
};
var wfblk = function(out, pos, dat) {
  var s = dat.length;
  var o = shft(pos + 2);
  out[o] = s & 255;
  out[o + 1] = s >> 8;
  out[o + 2] = out[o] ^ 255;
  out[o + 3] = out[o + 1] ^ 255;
  for (var i = 0; i < s; ++i)
    out[o + i + 4] = dat[i];
  return (o + 4 + s) * 8;
};
var wblk = function(dat, out, final, syms, lf, df, eb, li, bs, bl, p) {
  wbits(out, p++, final);
  ++lf[256];
  var _a2 = hTree(lf, 15), dlt = _a2.t, mlb = _a2.l;
  var _b2 = hTree(df, 15), ddt = _b2.t, mdb = _b2.l;
  var _c = lc(dlt), lclt = _c.c, nlc = _c.n;
  var _d = lc(ddt), lcdt = _d.c, ndc = _d.n;
  var lcfreq = new u16(19);
  for (var i = 0; i < lclt.length; ++i)
    ++lcfreq[lclt[i] & 31];
  for (var i = 0; i < lcdt.length; ++i)
    ++lcfreq[lcdt[i] & 31];
  var _e = hTree(lcfreq, 7), lct = _e.t, mlcb = _e.l;
  var nlcc = 19;
  for (; nlcc > 4 && !lct[clim[nlcc - 1]]; --nlcc)
    ;
  var flen = bl + 5 << 3;
  var ftlen = clen(lf, flt) + clen(df, fdt) + eb;
  var dtlen = clen(lf, dlt) + clen(df, ddt) + eb + 14 + 3 * nlcc + clen(lcfreq, lct) + 2 * lcfreq[16] + 3 * lcfreq[17] + 7 * lcfreq[18];
  if (bs >= 0 && flen <= ftlen && flen <= dtlen)
    return wfblk(out, p, dat.subarray(bs, bs + bl));
  var lm, ll, dm, dl;
  wbits(out, p, 1 + (dtlen < ftlen)), p += 2;
  if (dtlen < ftlen) {
    lm = hMap(dlt, mlb, 0), ll = dlt, dm = hMap(ddt, mdb, 0), dl = ddt;
    var llm = hMap(lct, mlcb, 0);
    wbits(out, p, nlc - 257);
    wbits(out, p + 5, ndc - 1);
    wbits(out, p + 10, nlcc - 4);
    p += 14;
    for (var i = 0; i < nlcc; ++i)
      wbits(out, p + 3 * i, lct[clim[i]]);
    p += 3 * nlcc;
    var lcts = [lclt, lcdt];
    for (var it = 0; it < 2; ++it) {
      var clct = lcts[it];
      for (var i = 0; i < clct.length; ++i) {
        var len = clct[i] & 31;
        wbits(out, p, llm[len]), p += lct[len];
        if (len > 15)
          wbits(out, p, clct[i] >> 5 & 127), p += clct[i] >> 12;
      }
    }
  } else {
    lm = flm, ll = flt, dm = fdm, dl = fdt;
  }
  for (var i = 0; i < li; ++i) {
    var sym = syms[i];
    if (sym > 255) {
      var len = sym >> 18 & 31;
      wbits16(out, p, lm[len + 257]), p += ll[len + 257];
      if (len > 7)
        wbits(out, p, sym >> 23 & 31), p += fleb[len];
      var dst = sym & 31;
      wbits16(out, p, dm[dst]), p += dl[dst];
      if (dst > 3)
        wbits16(out, p, sym >> 5 & 8191), p += fdeb[dst];
    } else {
      wbits16(out, p, lm[sym]), p += ll[sym];
    }
  }
  wbits16(out, p, lm[256]);
  return p + ll[256];
};
var deo = /* @__PURE__ */ new i32([65540, 131080, 131088, 131104, 262176, 1048704, 1048832, 2114560, 2117632]);
var et = /* @__PURE__ */ new u8(0);
var dflt = function(dat, lvl, plvl, pre, post, st) {
  var s = st.z || dat.length;
  var o = new u8(pre + s + 5 * (1 + Math.ceil(s / 7e3)) + post);
  var w = o.subarray(pre, o.length - post);
  var lst = st.l;
  var pos = (st.r || 0) & 7;
  if (lvl) {
    if (pos)
      w[0] = st.r >> 3;
    var opt = deo[lvl - 1];
    var n = opt >> 13, c = opt & 8191;
    var msk_1 = (1 << plvl) - 1;
    var prev = st.p || new u16(32768), head = st.h || new u16(msk_1 + 1);
    var bs1_1 = Math.ceil(plvl / 3), bs2_1 = 2 * bs1_1;
    var hsh = function(i2) {
      return (dat[i2] ^ dat[i2 + 1] << bs1_1 ^ dat[i2 + 2] << bs2_1) & msk_1;
    };
    var syms = new i32(25e3);
    var lf = new u16(288), df = new u16(32);
    var lc_1 = 0, eb = 0, i = st.i || 0, li = 0, wi = st.w || 0, bs = 0;
    for (; i + 2 < s; ++i) {
      var hv = hsh(i);
      var imod = i & 32767, pimod = head[hv];
      prev[imod] = pimod;
      head[hv] = imod;
      if (wi <= i) {
        var rem = s - i;
        if ((lc_1 > 7e3 || li > 24576) && (rem > 423 || !lst)) {
          pos = wblk(dat, w, 0, syms, lf, df, eb, li, bs, i - bs, pos);
          li = lc_1 = eb = 0, bs = i;
          for (var j = 0; j < 286; ++j)
            lf[j] = 0;
          for (var j = 0; j < 30; ++j)
            df[j] = 0;
        }
        var l = 2, d = 0, ch_1 = c, dif = imod - pimod & 32767;
        if (rem > 2 && hv == hsh(i - dif)) {
          var maxn = Math.min(n, rem) - 1;
          var maxd = Math.min(32767, i);
          var ml = Math.min(258, rem);
          while (dif <= maxd && --ch_1 && imod != pimod) {
            if (dat[i + l] == dat[i + l - dif]) {
              var nl = 0;
              for (; nl < ml && dat[i + nl] == dat[i + nl - dif]; ++nl)
                ;
              if (nl > l) {
                l = nl, d = dif;
                if (nl > maxn)
                  break;
                var mmd = Math.min(dif, nl - 2);
                var md = 0;
                for (var j = 0; j < mmd; ++j) {
                  var ti = i - dif + j & 32767;
                  var pti = prev[ti];
                  var cd = ti - pti & 32767;
                  if (cd > md)
                    md = cd, pimod = ti;
                }
              }
            }
            imod = pimod, pimod = prev[imod];
            dif += imod - pimod & 32767;
          }
        }
        if (d) {
          syms[li++] = 268435456 | revfl[l] << 18 | revfd[d];
          var lin = revfl[l] & 31, din = revfd[d] & 31;
          eb += fleb[lin] + fdeb[din];
          ++lf[257 + lin];
          ++df[din];
          wi = i + l;
          ++lc_1;
        } else {
          syms[li++] = dat[i];
          ++lf[dat[i]];
        }
      }
    }
    for (i = Math.max(i, wi); i < s; ++i) {
      syms[li++] = dat[i];
      ++lf[dat[i]];
    }
    pos = wblk(dat, w, lst, syms, lf, df, eb, li, bs, i - bs, pos);
    if (!lst) {
      st.r = pos & 7 | w[pos / 8 | 0] << 3;
      pos -= 7;
      st.h = head, st.p = prev, st.i = i, st.w = wi;
    }
  } else {
    for (var i = st.w || 0; i < s + lst; i += 65535) {
      var e = i + 65535;
      if (e >= s) {
        w[pos / 8 | 0] = lst;
        e = s;
      }
      pos = wfblk(w, pos + 1, dat.subarray(i, e));
    }
    st.i = s;
  }
  return slc(o, 0, pre + shft(pos) + post);
};
var crct = /* @__PURE__ */ function() {
  var t = new Int32Array(256);
  for (var i = 0; i < 256; ++i) {
    var c = i, k = 9;
    while (--k)
      c = (c & 1 && -306674912) ^ c >>> 1;
    t[i] = c;
  }
  return t;
}();
var crc = function() {
  var c = -1;
  return {
    p: function(d) {
      var cr = c;
      for (var i = 0; i < d.length; ++i)
        cr = crct[cr & 255 ^ d[i]] ^ cr >>> 8;
      c = cr;
    },
    d: function() {
      return ~c;
    }
  };
};
var dopt = function(dat, opt, pre, post, st) {
  if (!st) {
    st = { l: 1 };
    if (opt.dictionary) {
      var dict = opt.dictionary.subarray(-32768);
      var newDat = new u8(dict.length + dat.length);
      newDat.set(dict);
      newDat.set(dat, dict.length);
      dat = newDat;
      st.w = dict.length;
    }
  }
  return dflt(dat, opt.level == null ? 6 : opt.level, opt.mem == null ? st.l ? Math.ceil(Math.max(8, Math.min(13, Math.log(dat.length))) * 1.5) : 20 : 12 + opt.mem, pre, post, st);
};
var mrg = function(a, b) {
  var o = {};
  for (var k in a)
    o[k] = a[k];
  for (var k in b)
    o[k] = b[k];
  return o;
};
var b2 = function(d, b) {
  return d[b] | d[b + 1] << 8;
};
var b4 = function(d, b) {
  return (d[b] | d[b + 1] << 8 | d[b + 2] << 16 | d[b + 3] << 24) >>> 0;
};
var b8 = function(d, b) {
  return b4(d, b) + b4(d, b + 4) * 4294967296;
};
var wbytes = function(d, b, v) {
  for (; v; ++b)
    d[b] = v, v >>>= 8;
};
function deflateSync(data, opts) {
  return dopt(data, opts || {}, 0, 0);
}
function inflateSync(data, opts) {
  return inflt(data, { i: 2 }, opts && opts.out, opts && opts.dictionary);
}
var fltn = function(d, p, t, o) {
  for (var k in d) {
    var val = d[k], n = p + k, op = o;
    if (Array.isArray(val))
      op = mrg(o, val[1]), val = val[0];
    if (ArrayBuffer.isView(val))
      t[n] = [val, op];
    else {
      t[n += "/"] = [new u8(0), op];
      fltn(val, n, t, o);
    }
  }
};
var te = typeof TextEncoder != "undefined" && /* @__PURE__ */ new TextEncoder();
var td = typeof TextDecoder != "undefined" && /* @__PURE__ */ new TextDecoder();
var tds = 0;
try {
  td.decode(et, { stream: true });
  tds = 1;
} catch (e) {
}
var dutf8 = function(d) {
  for (var r = "", i = 0; ; ) {
    var c = d[i++];
    var eb = (c > 127) + (c > 223) + (c > 239);
    if (i + eb > d.length)
      return { s: r, r: slc(d, i - 1) };
    if (!eb)
      r += String.fromCharCode(c);
    else if (eb == 3) {
      c = ((c & 15) << 18 | (d[i++] & 63) << 12 | (d[i++] & 63) << 6 | d[i++] & 63) - 65536, r += String.fromCharCode(55296 | c >> 10, 56320 | c & 1023);
    } else if (eb & 1)
      r += String.fromCharCode((c & 31) << 6 | d[i++] & 63);
    else
      r += String.fromCharCode((c & 15) << 12 | (d[i++] & 63) << 6 | d[i++] & 63);
  }
};
function strToU8(str5, latin1) {
  if (latin1) {
    var ar_1 = new u8(str5.length);
    for (var i = 0; i < str5.length; ++i)
      ar_1[i] = str5.charCodeAt(i);
    return ar_1;
  }
  if (te)
    return te.encode(str5);
  var l = str5.length;
  var ar = new u8(str5.length + (str5.length >> 1));
  var ai = 0;
  var w = function(v) {
    ar[ai++] = v;
  };
  for (var i = 0; i < l; ++i) {
    if (ai + 5 > ar.length) {
      var n = new u8(ai + 8 + (l - i << 1));
      n.set(ar);
      ar = n;
    }
    var c = str5.charCodeAt(i);
    if (c < 128 || latin1)
      w(c);
    else if (c < 2048)
      w(192 | c >> 6), w(128 | c & 63);
    else if (c > 55295 && c < 57344)
      c = 65536 + (c & 1023 << 10) | str5.charCodeAt(++i) & 1023, w(240 | c >> 18), w(128 | c >> 12 & 63), w(128 | c >> 6 & 63), w(128 | c & 63);
    else
      w(224 | c >> 12), w(128 | c >> 6 & 63), w(128 | c & 63);
  }
  return slc(ar, 0, ai);
}
function strFromU8(dat, latin1) {
  if (latin1) {
    var r = "";
    for (var i = 0; i < dat.length; i += 16384)
      r += String.fromCharCode.apply(null, dat.subarray(i, i + 16384));
    return r;
  } else if (td) {
    return td.decode(dat);
  } else {
    var _a2 = dutf8(dat), s = _a2.s, r = _a2.r;
    if (r.length)
      err(8);
    return s;
  }
}
var slzh = function(d, b) {
  return b + 30 + b2(d, b + 26) + b2(d, b + 28);
};
var zh = function(d, b, z) {
  var fnl = b2(d, b + 28), efl = b2(d, b + 30), fn = strFromU8(d.subarray(b + 46, b + 46 + fnl), !(b2(d, b + 8) & 2048)), es = b + 46 + fnl;
  var _a2 = z64hs(d, es, efl, z, b4(d, b + 20), b4(d, b + 24), b4(d, b + 42)), sc = _a2[0], su = _a2[1], off = _a2[2];
  return [b2(d, b + 10), sc, su, fn, es + efl + b2(d, b + 32), off];
};
var z64hs = function(d, b, l, z, sc, su, off) {
  var nsc = sc == 4294967295, nsu = su == 4294967295, noff = off == 4294967295, e = b + l;
  var nf = nsc + nsu + noff;
  if (z && nf) {
    for (; b + 4 < e; b += 4 + b2(d, b + 2)) {
      if (b2(d, b) == 1) {
        return [
          nsc ? b8(d, b + 4 + 8 * nsu) : sc,
          nsu ? b8(d, b + 4) : su,
          noff ? b8(d, b + 4 + 8 * (nsu + nsc)) : off,
          1
        ];
      }
    }
    if (z < 2)
      err(13);
  }
  return [sc, su, off, 0];
};
var exfl = function(ex) {
  var le = 0;
  if (ex) {
    for (var k in ex) {
      var l = ex[k].length;
      if (l > 65535)
        err(9);
      le += l + 4;
    }
  }
  return le;
};
var wzh = function(d, b, f, fn, u, c, ce, co) {
  var fl2 = fn.length, ex = f.extra, col = co && co.length;
  var exl = exfl(ex);
  wbytes(d, b, ce != null ? 33639248 : 67324752), b += 4;
  if (ce != null)
    d[b++] = 20, d[b++] = f.os;
  d[b] = 20, b += 2;
  d[b++] = f.flag << 1 | (c < 0 && 8), d[b++] = u && 8;
  d[b++] = f.compression & 255, d[b++] = f.compression >> 8;
  var dt = new Date(f.mtime == null ? Date.now() : f.mtime), y = dt.getFullYear() - 1980;
  if (y < 0 || y > 119)
    err(10);
  wbytes(d, b, y << 25 | dt.getMonth() + 1 << 21 | dt.getDate() << 16 | dt.getHours() << 11 | dt.getMinutes() << 5 | dt.getSeconds() >> 1), b += 4;
  if (c != -1) {
    wbytes(d, b, f.crc);
    wbytes(d, b + 4, c < 0 ? -c - 2 : c);
    wbytes(d, b + 8, f.size);
  }
  wbytes(d, b + 12, fl2);
  wbytes(d, b + 14, exl), b += 16;
  if (ce != null) {
    wbytes(d, b, col);
    wbytes(d, b + 6, f.attrs);
    wbytes(d, b + 10, ce), b += 14;
  }
  d.set(fn, b);
  b += fl2;
  if (exl) {
    for (var k in ex) {
      var exf = ex[k], l = exf.length;
      wbytes(d, b, +k);
      wbytes(d, b + 2, l);
      d.set(exf, b + 4), b += 4 + l;
    }
  }
  if (col)
    d.set(co, b), b += col;
  return b;
};
var wzf = function(o, b, c, d, e) {
  wbytes(o, b, 101010256);
  wbytes(o, b + 8, c);
  wbytes(o, b + 10, c);
  wbytes(o, b + 12, d);
  wbytes(o, b + 16, e);
};
function zipSync(data, opts) {
  if (!opts)
    opts = {};
  var r = {};
  var files = [];
  fltn(data, "", r, opts);
  var o = 0;
  var tot = 0;
  for (var fn in r) {
    var _a2 = r[fn], file = _a2[0], p = _a2[1];
    var compression = p.level == 0 ? 0 : 8;
    var f = strToU8(fn), s = f.length;
    var com = p.comment, m = com && strToU8(com), ms = m && m.length;
    var exl = exfl(p.extra);
    if (s > 65535)
      err(11);
    var d = compression ? deflateSync(file, p) : file, l = d.length;
    var c = crc();
    c.p(file);
    files.push(mrg(p, {
      size: file.length,
      crc: c.d(),
      c: d,
      f,
      m,
      u: s != fn.length || m && com.length != ms,
      o,
      compression
    }));
    o += 30 + s + exl + l;
    tot += 76 + 2 * (s + exl) + (ms || 0) + l;
  }
  var out = new u8(tot + 22), oe = o, cdl = tot - o;
  for (var i = 0; i < files.length; ++i) {
    var f = files[i];
    wzh(out, f.o, f, f.f, f.u, f.c.length);
    var badd = 30 + f.f.length + exfl(f.extra);
    out.set(f.c, f.o + badd);
    wzh(out, o, f, f.f, f.u, f.c.length, f.o, f.m), o += 16 + badd + (f.m ? f.m.length : 0);
  }
  wzf(out, o, files.length, cdl, oe);
  return out;
}
function unzipSync(data, opts) {
  var files = {};
  var e = data.length - 22;
  for (; b4(data, e) != 101010256; --e) {
    if (!e || data.length - e > 65558)
      err(13);
  }
  ;
  var c = b2(data, e + 8);
  if (!c)
    return {};
  var o = b4(data, e + 16);
  var z = b4(data, e - 20) == 117853008;
  if (z) {
    var ze = b4(data, e - 12);
    z = b4(data, ze) == 101075792;
    if (z) {
      c = b4(data, ze + 32);
      o = b4(data, ze + 48);
    }
  }
  var fltr = opts && opts.filter;
  for (var i = 0; i < c; ++i) {
    var _a2 = zh(data, o, z), c_2 = _a2[0], sc = _a2[1], su = _a2[2], fn = _a2[3], no = _a2[4], off = _a2[5], b = slzh(data, off);
    o = no;
    if (!fltr || fltr({
      name: fn,
      size: sc,
      originalSize: su,
      compression: c_2
    })) {
      if (!c_2)
        files[fn] = slc(data, b, b + sc);
      else if (c_2 == 8)
        files[fn] = inflateSync(data.subarray(b, b + sc), { out: new u8(su) });
      else
        err(14, "unknown compression type " + c_2);
    }
  }
  return files;
}

// ../tavern-format/lib/charx.js
var CharxFormatError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "CharxFormatError";
  }
};
function decodeCharx(bytes) {
  let files;
  try {
    files = unzipSync(bytes);
  } catch (cause) {
    throw new CharxFormatError(`not a valid zip: ${String(cause)}`);
  }
  const cardJson = files["card.json"];
  if (cardJson === void 0)
    throw new CharxFormatError("CHARX has no 'card.json' at zip root");
  const card = decodeCharacterCard(JSON.parse(strFromU8(cardJson)));
  const assetPaths = Object.keys(files).filter((p) => p !== "card.json");
  return { card, assetPaths };
}
function decodeCharxAsset(bytes, path2) {
  let files;
  try {
    files = unzipSync(bytes);
  } catch (cause) {
    throw new CharxFormatError(`not a valid zip: ${String(cause)}`);
  }
  const asset = files[path2];
  if (asset === void 0)
    throw new CharxFormatError(`CHARX has no asset '${path2}'`);
  return asset;
}
function encodeCharx(ir, assets) {
  const files = {
    "card.json": strToU8(JSON.stringify(encodeCharacterCardJson(ir)))
  };
  for (const asset of assets ?? [])
    files[asset.path] = asset.data;
  return zipSync(files);
}

// ../tavern-format/lib/group.js
var GroupFormatError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "GroupFormatError";
  }
};
function parseGroupFile(obj, name2) {
  const groupName = str3(obj["name"]) || (name2 ?? "");
  if (groupName === "")
    throw new GroupFormatError("group has no name");
  const membersRaw = Array.isArray(obj["members"]) ? obj["members"] : [];
  const members = [];
  let droppedMembers = 0;
  for (const member of membersRaw) {
    if (typeof member === "string") {
      const trimmed = member.trim();
      if (trimmed !== "")
        members.push(trimmed);
    } else {
      droppedMembers += 1;
    }
  }
  const KNOWN_GROUP_FIELDS = [
    "members",
    "id",
    "name",
    "allow_self_responses",
    "activation_strategy",
    "disabled_members",
    "chat_id",
    "chats",
    "auto_mode_delay"
  ];
  const extra = {};
  for (const [key, value] of Object.entries(obj)) {
    if (!KNOWN_GROUP_FIELDS.includes(key))
      extra[key] = value;
  }
  const strategy = num2(obj["activation_strategy"], 1);
  const chats = Array.isArray(obj["chats"]) ? obj["chats"].filter((value) => typeof value === "string") : [];
  return {
    id: str3(obj["id"]) || `group-${groupName}`,
    name: groupName,
    members,
    allowSelfResponses: bool2(obj["allow_self_responses"], false),
    activationStrategy: strategy === 2 ? 2 : 1,
    disabledMembers: Array.isArray(obj["disabled_members"]) ? obj["disabled_members"].filter((value) => typeof value === "string") : [],
    chatId: str3(obj["chat_id"]),
    chats,
    autoModeDelay: num2(obj["auto_mode_delay"], 3),
    extra: Object.keys(extra).length > 0 ? extra : void 0,
    ...droppedMembers > 0 ? { droppedMembers } : {}
  };
}
function serializeGroupFile(ir) {
  return {
    ...ir.extra ?? {},
    id: ir.id,
    name: ir.name,
    members: [...ir.members],
    allow_self_responses: ir.allowSelfResponses,
    activation_strategy: ir.activationStrategy,
    disabled_members: [...ir.disabledMembers],
    chat_id: ir.chatId,
    chats: [...ir.chats],
    auto_mode_delay: ir.autoModeDelay
  };
}
function str3(value) {
  return typeof value === "string" ? value : "";
}
function num2(value, fallback) {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}
function bool2(value, fallback) {
  return typeof value === "boolean" ? value : fallback;
}

// ../tavern-format/lib/regex-script.js
var RegexPlacement = {
  USER_INPUT: 1,
  AI_OUTPUT: 2,
  SLASH_COMMAND: 3,
  WORLD_INFO: 5,
  REASONING: 6
};
var RegexScriptFormatError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "RegexScriptFormatError";
  }
};
var KNOWN_FIELDS2 = /* @__PURE__ */ new Set([
  "id",
  "scriptName",
  "findRegex",
  "replaceString",
  "trimStrings",
  "placement",
  "disabled",
  "markdownOnly",
  "promptOnly",
  "runOnEdit",
  "substituteRegex",
  "minDepth",
  "maxDepth"
]);
var PLACEMENT_VALUES = /* @__PURE__ */ new Set([1, 2, 3, 5, 6]);
function parseRegexScripts(input) {
  let list;
  if (Array.isArray(input))
    list = input;
  else if (typeof input === "object" && input !== null) {
    const obj = input;
    if (Array.isArray(obj["scripts"]))
      list = obj["scripts"];
    else if (Array.isArray(obj["regex_scripts"]))
      list = obj["regex_scripts"];
    else
      list = [input];
  } else {
    throw new RegexScriptFormatError("regex scripts input must be an array or object");
  }
  return list.map((item, index) => parseRegexScript(item, index));
}
function parseRegexScript(raw, index = 0) {
  if (typeof raw !== "object" || raw === null) {
    throw new RegexScriptFormatError(`regex script ${index} is not an object`);
  }
  const obj = raw;
  const findRegex = str4(obj["findRegex"]);
  if (findRegex === "")
    throw new RegexScriptFormatError(`regex script ${index} has empty findRegex`);
  const extra = {};
  for (const [k, v] of Object.entries(obj)) {
    if (!KNOWN_FIELDS2.has(k))
      extra[k] = v;
  }
  const placement = (Array.isArray(obj["placement"]) ? obj["placement"] : [obj["placement"]]).map((value) => typeof value === "number" && Number.isFinite(value) ? value : 0).filter((value) => PLACEMENT_VALUES.has(value));
  return {
    id: str4(obj["id"]) || `regex-${index}-${str4(obj["scriptName"]) || "script"}`,
    scriptName: str4(obj["scriptName"]) || str4(obj["script_name"]) || `Script ${index + 1}`,
    findRegex,
    replaceString: str4(obj["replaceString"]),
    trimStrings: Array.isArray(obj["trimStrings"]) ? obj["trimStrings"].filter((value) => typeof value === "string") : [],
    placement: placement.length > 0 ? [...new Set(placement)] : [RegexPlacement.AI_OUTPUT],
    disabled: bool3(obj["disabled"], false),
    markdownOnly: bool3(obj["markdownOnly"], false),
    promptOnly: bool3(obj["promptOnly"], false),
    runOnEdit: bool3(obj["runOnEdit"], false),
    substituteRegex: bool3(obj["substituteRegex"], false),
    minDepth: numOrNull(obj["minDepth"]),
    maxDepth: numOrNull(obj["maxDepth"]),
    extra: Object.keys(extra).length > 0 ? extra : void 0
  };
}
function str4(value) {
  return typeof value === "string" ? value : "";
}
function bool3(value, fallback) {
  return typeof value === "boolean" ? value : fallback;
}
function numOrNull(value) {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

// ../tavern-store/src/store.ts
var ChatRevisionConflictError = class extends Error {
  constructor(expectedRevision, actualRevision) {
    super("Chat changed in another tab. Reloaded the latest version; review it before retrying.");
    this.expectedRevision = expectedRevision;
    this.actualRevision = actualRevision;
    this.name = "ChatRevisionConflictError";
  }
  code = "CHAT_REVISION_CONFLICT";
};
var DEFAULT_STATE = {
  activeWorlds: [],
  sessionBindings: {},
  defaultArchitecture: "agent-tavern",
  defaultContextMode: "dsh-native",
  agentTavernPreloadAssets: false,
  agentTavernAllowGlobalWrites: false,
  modelSelections: {},
  chats: {},
  regexScripts: [],
  scriptGlobals: {},
  pipelineMode: "chat"
};
var TavernStore = class _TavernStore {
  constructor(root) {
    this.root = root;
  }
  chatMutationTail = Promise.resolve();
  stateMutationTail = Promise.resolve();
  static async open(root) {
    for (const dir of ["characters", "worlds", "presets", "chats", "personas", "groups", "personas/avatars"]) {
      await fs.mkdir(path.join(root, dir), { recursive: true });
    }
    return new _TavernStore(root);
  }
  /* ------------------------------ 角色 ------------------------------ */
  /** 导入角色卡：PNG/CHARX 原字节落盘保留资源；JSON 对象序列化落盘。重名覆盖。
   *  卡内嵌角色书自动物化为世界书文件并写回 extensions.world 链接（对齐 ST 导入语义）。
   *  卡内嵌 regex_scripts 物化为全局脚本（按 scriptName 合并）。 */
  async importCharacter(source) {
    let bytes;
    let kind;
    let card;
    let charxAssets;
    if (source instanceof Uint8Array) {
      if (source[0] === 137 && source[1] === 80) {
        bytes = source;
        kind = "png";
        card = decodeCharacterCard(bytes);
      } else if (source[0] === 80 && source[1] === 75) {
        bytes = source;
        kind = "charx";
        const decoded = decodeCharx(bytes);
        card = decoded.card;
        charxAssets = decoded.assetPaths.map((assetPath) => ({ path: assetPath, data: decodeCharxAsset(bytes, assetPath) }));
      } else {
        card = decodeCharacterCard(JSON.parse(Buffer.from(source).toString("utf8")));
        bytes = jsonBytes(encodeCharacterCardJson(card));
        kind = "json";
      }
    } else {
      card = decodeCharacterCard(source);
      bytes = jsonBytes(encodeCharacterCardJson(card));
      kind = "json";
    }
    const importedWorld = await this.materializeEmbeddedBook(card);
    const importedRegex = await this.importEmbeddedRegex(card);
    if (importedWorld !== void 0) {
      bytes = kind === "png" ? encodeCharacterCardPng(card, bytes) : kind === "charx" ? encodeCharx(card, charxAssets) : jsonBytes(encodeCharacterCardJson(card));
    }
    const stem = safeFileName(card.data.name);
    const fileName = `${stem}.${kind}`;
    await this.writeAtomic(path.join(this.root, "characters", fileName), bytes);
    await Promise.all(["png", "json", "charx"].filter((other) => other !== kind).map((other) => fs.rm(path.join(this.root, "characters", `${stem}.${other}`), { force: true })));
    return { fileName, card, importedWorld, importedRegex };
  }
  /**
   * 卡内嵌角色书 → worlds/ 下的世界书文件（重名覆盖，导入以卡内嵌书为准），
   * 并把 extensions.world 链接写回卡数据。返回物化的世界书名；无内嵌书时为 undefined。
   * 命名：已有链接名 > 内嵌书自身名 > 角色名。
   */
  async materializeEmbeddedBook(card) {
    const book = card.data.characterBook;
    if (!book) return void 0;
    const rawLinked = card.data.extensions["world"];
    const linkedName = typeof rawLinked === "string" ? rawLinked.trim() : "";
    const bookName = linkedName !== "" ? linkedName : typeof book.name === "string" && book.name.trim() !== "" ? book.name.trim() : card.data.name;
    await this.putWorld({ ...parseCharacterBook(book), name: bookName });
    if (linkedName === "") {
      card.data.extensions = { ...card.data.extensions, world: bookName };
    }
    return bookName;
  }
  /** 卡内嵌 regex_scripts 物化为全局脚本；脚本格式非法时整体跳过，不阻断角色导入。 */
  async importEmbeddedRegex(card) {
    const embedded = card.data.extensions["regex_scripts"];
    if (embedded === void 0 || embedded === null) return 0;
    try {
      return await this.importRegexScripts(embedded);
    } catch {
      return 0;
    }
  }
  /** 导出角色卡 PNG（带模板图）；无图像模板时导出 JSON。 */
  async exportCharacter(name2, template) {
    const file = await this.getCharacter(name2);
    if (file === void 0) throw new Error(`character '${name2}' not found`);
    if (file.kind === "png") {
      const bytes = await fs.readFile(path.join(this.root, "characters", file.fileName));
      if (template === void 0) return bytes;
      return encodeCharacterCardPng(file.card, bytes);
    }
    if (file.kind === "charx" && template === void 0) {
      return new Uint8Array(await fs.readFile(path.join(this.root, "characters", file.fileName)));
    }
    if (template !== void 0) return encodeCharacterCardPng(file.card, template);
    return new Uint8Array(Buffer.from(JSON.stringify(encodeCharacterCardJson(file.card), null, 2), "utf8"));
  }
  /**
   * 保存已编辑的角色卡，并尽量保留原始容器：PNG 继续写回原图的 chunks，
   * CHARX 继续保留 zip 内全部资源；名称变更时同步迁移文件名。
   */
  async updateCharacter(name2, source) {
    const current = await this.getCharacter(name2);
    if (current === void 0) throw new Error(`character '${name2}' not found`);
    const incomingData = source.data;
    const card = typeof incomingData === "object" && incomingData !== null && !Array.isArray(incomingData) && Object.prototype.hasOwnProperty.call(incomingData, "firstMes") ? {
      ...current.card,
      spec: source.spec ?? current.card.spec,
      specVersion: typeof source.specVersion === "string" ? source.specVersion : current.card.specVersion,
      data: { ...current.card.data, ...incomingData },
      raw: structuredClone(current.card.raw)
    } : decodeCharacterCard(source);
    if (typeof card.data.name !== "string" || card.data.name.trim() === "") {
      throw new Error("character name cannot be empty");
    }
    const nextStem = safeFileName(card.data.name);
    const currentStem = safeFileName(name2);
    const collision = await this.getCharacter(card.data.name);
    if (collision !== void 0 && nextStem !== currentStem) {
      throw new Error(`character '${card.data.name}' already exists`);
    }
    let bytes;
    let kind = current.kind;
    const original = new Uint8Array(await fs.readFile(path.join(this.root, "characters", current.fileName)));
    if (current.kind === "png") {
      bytes = encodeCharacterCardPng(card, original);
    } else if (current.kind === "charx") {
      const decoded = decodeCharx(original);
      bytes = encodeCharx(card, decoded.assetPaths.map((assetPath) => ({ path: assetPath, data: decodeCharxAsset(original, assetPath) })));
    } else {
      bytes = jsonBytes(encodeCharacterCardJson(card));
    }
    await this.writeAtomic(path.join(this.root, "characters", `${nextStem}.${kind}`), bytes);
    if (currentStem !== nextStem || current.kind !== kind) {
      await fs.rm(path.join(this.root, "characters", current.fileName), { force: true });
    }
    if (currentStem !== nextStem) {
      try {
        await fs.access(path.join(this.root, "chats", nextStem));
      } catch (cause) {
        if (cause.code !== "ENOENT") throw cause;
        try {
          await fs.rename(path.join(this.root, "chats", currentStem), path.join(this.root, "chats", nextStem));
        } catch (renameCause) {
          if (renameCause.code !== "ENOENT") throw renameCause;
        }
      }
    }
    for (const other of ["png", "json", "charx"].filter((other2) => other2 !== kind)) {
      await fs.rm(path.join(this.root, "characters", `${nextStem}.${other}`), { force: true });
    }
    const saved = await this.getCharacter(card.data.name);
    if (saved === void 0) throw new Error(`character '${card.data.name}' could not be reloaded`);
    return saved;
  }
  async listCharacters() {
    const files = await this.listDir("characters");
    return [...new Set(files.filter((f) => /\.(png|json|charx)$/.test(f)).map((f) => f.replace(/\.(png|json|charx)$/, "")))].sort();
  }
  async getCharacter(name2) {
    for (const kind of ["png", "charx", "json"]) {
      const fileName = `${safeFileName(name2)}.${kind}`;
      try {
        const bytes = new Uint8Array(await fs.readFile(path.join(this.root, "characters", fileName)));
        const card = kind === "png" ? decodeCharacterCard(bytes) : kind === "charx" ? decodeCharx(bytes).card : decodeCharacterCard(JSON.parse(Buffer.from(bytes).toString("utf8")));
        return { fileName, kind, card };
      } catch (cause) {
        if (cause.code !== "ENOENT") throw cause;
      }
    }
    return void 0;
  }
  async deleteCharacter(name2) {
    let deleted = false;
    for (const kind of ["png", "json", "charx"]) {
      const file = path.join(this.root, "characters", `${safeFileName(name2)}.${kind}`);
      try {
        await fs.unlink(file);
        deleted = true;
      } catch (cause) {
        if (cause.code !== "ENOENT") throw cause;
      }
    }
    if (deleted) {
      await fs.rm(path.join(this.root, "chats", safeFileName(name2)), { recursive: true, force: true });
    }
    return deleted;
  }
  /* ----------------------------- 世界书 ----------------------------- */
  async putWorld(book) {
    await this.writeAtomic(
      path.join(this.root, "worlds", `${safeFileName(book.name)}.json`),
      jsonBytes(serializeWorldInfoFile(book))
    );
  }
  /** 导入 ST 世界书文件对象。 */
  async importWorldFile(name2, obj) {
    const ir = parseWorldInfoFile(name2, obj);
    await this.putWorld(ir);
    return ir;
  }
  async listWorlds() {
    const files = await this.listDir("worlds");
    return files.filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, "")).sort();
  }
  async getWorld(name2) {
    const bytes = await this.tryRead(path.join(this.root, "worlds", `${safeFileName(name2)}.json`));
    if (bytes === void 0) return void 0;
    return parseWorldInfoFile(name2, JSON.parse(Buffer.from(bytes).toString("utf8")));
  }
  async exportWorld(name2) {
    const book = await this.getWorld(name2);
    if (book === void 0) throw new Error(`world '${name2}' not found`);
    return jsonBytes(serializeWorldInfoFile(book));
  }
  async deleteWorld(name2) {
    await fs.rm(path.join(this.root, "worlds", `${safeFileName(name2)}.json`), { force: true });
  }
  /* ------------------------------ 聊天 ------------------------------ */
  async createChat(characterName, header, messages = []) {
    return this.mutateChat(async () => {
      const dir = path.join(this.root, "chats", safeFileName(characterName));
      await fs.mkdir(dir, { recursive: true });
      const id = `${timestamp()}.jsonl`;
      await this.writeAtomic(path.join(dir, id), chatBytes({ header, messages }));
      return id;
    });
  }
  async saveChat(characterName, chatId, log, expectedRevision) {
    return this.mutateChat(async () => {
      const dir = path.join(this.root, "chats", safeFileName(characterName));
      const file = path.join(dir, safeChatFileName(chatId));
      await this.assertChatRevision(file, expectedRevision);
      const bytes = chatBytes(log);
      await this.writeAtomic(file, bytes);
      return chatRevision(bytes);
    });
  }
  async getChat(characterName, chatId) {
    return (await this.getChatSnapshot(characterName, chatId))?.chat;
  }
  async getChatSnapshot(characterName, chatId) {
    const bytes = await this.tryRead(path.join(this.root, "chats", safeFileName(characterName), safeChatFileName(chatId)));
    if (bytes === void 0) return void 0;
    return {
      chat: parseChatLog(Buffer.from(bytes).toString("utf8")),
      revision: chatRevision(bytes)
    };
  }
  async listChats(characterName) {
    const dir = path.join(this.root, "chats", safeFileName(characterName));
    try {
      const files = await fs.readdir(dir);
      return files.filter((f) => f.endsWith(".jsonl")).sort();
    } catch (cause) {
      if (cause.code === "ENOENT") return [];
      throw cause;
    }
  }
  async renameChat(characterName, chatId, nextChatId, expectedRevision) {
    await this.mutateChat(async () => {
      const dir = path.join(this.root, "chats", safeFileName(characterName));
      const source = path.join(dir, safeChatFileName(chatId));
      const target = path.join(dir, safeChatFileName(nextChatId));
      await this.assertChatRevision(source, expectedRevision);
      if (source === target) return;
      if (await this.tryRead(target)) throw new Error(`chat '${nextChatId}' already exists`);
      await fs.rename(source, target);
    });
  }
  async deleteChat(characterName, chatId, expectedRevision) {
    return this.mutateChat(async () => {
      const file = path.join(this.root, "chats", safeFileName(characterName), safeChatFileName(chatId));
      try {
        await this.assertChatRevision(file, expectedRevision);
        await fs.unlink(file);
        return true;
      } catch (cause) {
        if (cause.code === "ENOENT") return false;
        throw cause;
      }
    });
  }
  /* ------------------------------ 群组 ------------------------------ */
  async putGroup(group) {
    await this.writeAtomic(
      path.join(this.root, "groups", `${safeFileName(group.name)}.json`),
      jsonBytes(serializeGroupFile(group))
    );
  }
  async getGroup(name2) {
    const bytes = await this.tryRead(path.join(this.root, "groups", `${safeFileName(name2)}.json`));
    if (bytes === void 0) return void 0;
    return parseGroupFile(JSON.parse(Buffer.from(bytes).toString("utf8")), name2);
  }
  async listGroups() {
    const files = await this.listDir("groups");
    return files.filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, "")).sort();
  }
  async deleteGroup(name2) {
    await fs.rm(path.join(this.root, "groups", `${safeFileName(name2)}.json`), { force: true });
  }
  /* ------------------------------ 预设 ------------------------------ */
  /** 预设按原样 JSON 存取（含采样参数与 prompts/prompt_order 全量）。 */
  async putPreset(name2, preset) {
    await this.writeAtomic(path.join(this.root, "presets", `${safeFileName(name2)}.json`), jsonBytes(preset));
  }
  async getPreset(name2) {
    const bytes = await this.tryRead(path.join(this.root, "presets", `${safeFileName(name2)}.json`));
    if (bytes === void 0) return void 0;
    return JSON.parse(Buffer.from(bytes).toString("utf8"));
  }
  async exportPreset(name2) {
    const preset = await this.getPreset(name2);
    if (preset === void 0) throw new Error(`preset '${name2}' not found`);
    return jsonBytes(preset);
  }
  async listPresets() {
    const files = await this.listDir("presets");
    return files.filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, "")).sort();
  }
  async deletePreset(name2) {
    await fs.rm(path.join(this.root, "presets", `${safeFileName(name2)}.json`), { force: true });
  }
  /* ----------------------------- persona ----------------------------- */
  async putPersona(persona, avatar) {
    await this.writeAtomic(path.join(this.root, "personas", `${safeFileName(persona.name)}.json`), jsonBytes(persona));
    if (avatar !== void 0) {
      await this.writeAtomic(path.join(this.root, "personas", "avatars", `${safeFileName(persona.name)}.png`), avatar);
    }
  }
  /**
   * 导入 persona PNG：内嵌 `chara`/`ccv3` 的 description 作为人设描述
   * （ST persona 导入行为），文件名 stem 作为 persona 名；头像原字节保存。
   */
  async importPersonaPng(bytes, fallbackName) {
    let description = "";
    try {
      const card = decodeCharacterCard(bytes);
      description = card.data.description;
    } catch {
    }
    const name2 = safeFileName(fallbackName) || "Persona";
    const persona = { name: name2, description, position: 0, hasAvatar: true };
    await this.putPersona(persona, bytes);
    return persona;
  }
  async getPersonaAvatar(name2) {
    return this.tryRead(path.join(this.root, "personas", "avatars", `${safeFileName(name2)}.png`));
  }
  async getPersona(name2) {
    const bytes = await this.tryRead(path.join(this.root, "personas", `${safeFileName(name2)}.json`));
    if (bytes === void 0) return void 0;
    return JSON.parse(Buffer.from(bytes).toString("utf8"));
  }
  async listPersonas() {
    const files = await this.listDir("personas");
    return files.filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, "")).sort();
  }
  async deletePersona(name2) {
    let deleted = false;
    const json = path.join(this.root, "personas", `${safeFileName(name2)}.json`);
    const avatar = path.join(this.root, "personas", "avatars", `${safeFileName(name2)}.png`);
    try {
      await fs.unlink(json);
      deleted = true;
    } catch (cause) {
      if (cause.code !== "ENOENT") throw cause;
    }
    await fs.rm(avatar, { force: true });
    return deleted;
  }
  /* ------------------------------ 分支 ------------------------------ */
  /**
   * 从 messageId（含）截断复制为新聊天；chat_metadata.bookmark_link 记录回链。
   * 分支命名 `${stem} - branch N.jsonl`（N 递增至不冲突，字符集安全）。
   */
  async branchChat(characterName, chatId, messageId, expectedRevision, name2, metadata) {
    return this.mutateChat(async () => {
      const dir = path.join(this.root, "chats", safeFileName(characterName));
      const source = path.join(dir, safeChatFileName(chatId));
      await this.assertChatRevision(source, expectedRevision);
      const bytes = await this.tryRead(source);
      if (bytes === void 0) throw new Error(`chat '${chatId}' not found`);
      const log = parseChatLog(Buffer.from(bytes).toString("utf8"));
      if (messageId < 0 || messageId >= log.messages.length) {
        throw new Error(`branch messageId ${messageId} out of range (0..${log.messages.length - 1})`);
      }
      const branchMessages = log.messages.slice(0, messageId + 1).map((m) => ({ ...m }));
      const header = structuredClone(log.header);
      header.chat_metadata = {
        ...header.chat_metadata ?? {},
        bookmark_link: { character: characterName, chatId, messageId },
        ...metadata ?? {}
      };
      const stem = (name2 !== void 0 && name2.trim() !== "" ? name2.trim() : chatId.replace(/\.jsonl$/i, "")).replace(/\.jsonl$/i, "");
      const safeStem = stem.replace(/[^A-Za-z0-9@ _.-]/g, "_").slice(0, 80) || "chat";
      let nextId = `${safeStem} - branch 1.jsonl`;
      let counter = 1;
      while (await this.tryRead(path.join(dir, nextId)) !== void 0) {
        counter += 1;
        nextId = `${safeStem} - branch ${counter}.jsonl`;
      }
      const branchLog = { header, messages: branchMessages };
      await this.writeAtomic(path.join(dir, nextId), chatBytes(branchLog));
      return { chatId: nextId, chat: branchLog };
    });
  }
  /* ------------------------------ 状态 ------------------------------ */
  async getState() {
    await this.stateMutationTail.catch(() => {
    });
    return this.readState();
  }
  async patchState(patch) {
    return this.updateState(() => patch);
  }
  async updateState(update) {
    return this.mutateState(async () => {
      const current = await this.readState();
      const next = { ...current, ...update(structuredClone(current)) };
      await this.writeAtomic(path.join(this.root, "state.json"), jsonBytes(next));
      return next;
    });
  }
  /** 解析 regex 脚本并合并进全局状态（scriptName 相同即覆盖）；返回导入的脚本数。 */
  async importRegexScripts(input) {
    const imported = parseRegexScripts(input);
    if (imported.length === 0) return 0;
    await this.updateState((current) => ({
      regexScripts: mergeRegexScripts(current.regexScripts, imported)
    }));
    return imported.length;
  }
  /* ------------------------------ 内部 ------------------------------ */
  async readState() {
    const bytes = await this.tryRead(path.join(this.root, "state.json"));
    if (bytes === void 0) return structuredClone(DEFAULT_STATE);
    const parsed = JSON.parse(Buffer.from(bytes).toString("utf8"));
    return {
      ...structuredClone(DEFAULT_STATE),
      ...parsed,
      activeWorlds: parsed.activeWorlds ?? [],
      sessionBindings: normalizeSessionBindings(parsed.sessionBindings),
      defaultArchitecture: parsed.defaultArchitecture === "st" ? "st" : "agent-tavern",
      defaultContextMode: parsed.defaultContextMode === "agent-managed" ? "agent-managed" : "dsh-native",
      agentTavernPreloadAssets: parsed.agentTavernPreloadAssets === true,
      agentTavernAllowGlobalWrites: parsed.agentTavernAllowGlobalWrites === true,
      modelSelections: parsed.modelSelections ?? {},
      chats: parsed.chats ?? {},
      regexScripts: parsed.regexScripts ?? [],
      scriptGlobals: parsed.scriptGlobals ?? {},
      pipelineMode: parsed.pipelineMode === "text" ? "text" : "chat"
    };
  }
  async assertChatRevision(file, expectedRevision) {
    if (expectedRevision === void 0) return;
    const current = await this.tryRead(file);
    const actualRevision = current === void 0 ? void 0 : chatRevision(current);
    if (actualRevision !== expectedRevision) {
      throw new ChatRevisionConflictError(expectedRevision, actualRevision);
    }
  }
  mutateChat(operation) {
    const result = this.chatMutationTail.catch(() => {
    }).then(operation);
    this.chatMutationTail = result.then(() => {
    }, () => {
    });
    return result;
  }
  mutateState(operation) {
    const result = this.stateMutationTail.catch(() => {
    }).then(operation);
    this.stateMutationTail = result.then(() => {
    }, () => {
    });
    return result;
  }
  async listDir(dir) {
    try {
      return await fs.readdir(path.join(this.root, dir));
    } catch (cause) {
      if (cause.code === "ENOENT") return [];
      throw cause;
    }
  }
  async tryRead(file) {
    try {
      return new Uint8Array(await fs.readFile(file));
    } catch (cause) {
      if (cause.code === "ENOENT") return void 0;
      throw cause;
    }
  }
  async writeAtomic(file, bytes) {
    const tmp = `${file}.${process.pid}.${Date.now()}.tmp`;
    await fs.writeFile(tmp, bytes);
    await fs.rename(tmp, file);
  }
};
function normalizeTavernSessionBinding(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return void 0;
  const candidate = value;
  if (typeof candidate.character !== "string" || candidate.character.trim() === "") return void 0;
  if (typeof candidate.chatId !== "string" || candidate.chatId.trim() === "") return void 0;
  const base = {
    character: candidate.character,
    chatId: candidate.chatId,
    ...candidate.group === true ? { group: true } : {}
  };
  if (candidate.architecture === "agent-tavern" && base.group !== true) {
    return {
      ...base,
      architecture: "agent-tavern",
      contextMode: candidate.contextMode === "agent-managed" ? "agent-managed" : "dsh-native",
      ...candidate.initializationPending === true ? { initializationPending: true } : {}
    };
  }
  return { ...base, architecture: "st" };
}
function normalizeSessionBindings(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return {};
  return Object.fromEntries(Object.entries(value).map(([sessionId, binding]) => [sessionId, normalizeTavernSessionBinding(binding)]).filter((entry) => entry[1] !== void 0));
}
function mergeRegexScripts(current, imported) {
  const merged = [...current];
  for (const script of imported) {
    const index = merged.findIndex((item) => item.scriptName === script.scriptName);
    if (index >= 0) merged[index] = script;
    else merged.push(script);
  }
  return merged;
}
function safeFileName(name2) {
  const cleaned = name2.replace(/[\\/:*?"<>|\u0000-\u001f]/g, "_").trim();
  return cleaned.length > 0 ? cleaned.slice(0, 120) : "_unnamed";
}
function timestamp() {
  const d = /* @__PURE__ */ new Date();
  const pad = (n, w = 2) => String(n).padStart(w, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}@${pad(d.getHours())}h ${pad(d.getMinutes())}m ${pad(d.getSeconds())}s ${pad(d.getMilliseconds(), 3)}ms`;
}
function safeChatFileName(name2) {
  if (!/^[A-Za-z0-9@ _.-]+\.jsonl$/.test(name2) || name2.includes("..")) throw new Error("invalid chat id");
  return name2;
}
function chatBytes(log) {
  return new Uint8Array(Buffer.from(serializeChatLog(log), "utf8"));
}
function chatRevision(bytes) {
  return createHash("sha256").update(bytes).digest("base64url");
}
function jsonBytes(obj) {
  return new Uint8Array(Buffer.from(JSON.stringify(obj, null, 2), "utf8"));
}

// ../tavern-store/src/memory.ts
var MAX_CONTENT = 64 * 1024;

// ../tavern-store/src/variable.ts
var MAX_VALUE_BYTES = 32 * 1024;
var MAX_SCOPE_BYTES = 256 * 1024;

// src/compaction/shared.ts
var SUMMARY_OPEN_TAG = "<compacted-summary>";
var RP_COMPACTION_INSTRUCTION = [
  "You are now acting as the compaction curator for this AgentTavern roleplay session. Condense the conversation ABOVE into a structured checkpoint that lets the same character resume the story with no loss of essential context.",
  "",
  'Output EXACTLY the Markdown structure below: keep every section, in order. Use terse bullets, not prose paragraphs. Write "(none)" for an empty section \u2014 never drop a section.',
  "",
  "## Story So Far",
  "- [the plot in order: key events, turning points, and what changed for the user's character]",
  "",
  "## Characters",
  "- [per recurring character: identity, relationship to the user's character, current location, state (health, possessions, mood), promises and debts]",
  "",
  "## World Canon",
  "- [established facts from world books and narration: places, factions, powers, items, history. Only what was established; never invent.]",
  "",
  "## Open Threads",
  "- [unresolved situations, unanswered questions, foreshadowing, pending decisions]",
  "",
  "## Current Scene",
  "- [time, place, who is present, the exact situation at this checkpoint]",
  "",
  "## Memory Maintenance",
  "- [what was recorded with the memory or variable tools, and which significant facts above are still unrecorded and should be written next]",
  "",
  "## Critical Context",
  "- [user instructions about style, pacing, content boundaries, and anything the user asked to remember]",
  "",
  "Rules:",
  "- Write in the same language as the conversation.",
  "- Preserve names, titles, numbers, and quoted phrases verbatim.",
  "- Record only what the conversation established; do not add interpretation or invent facts.",
  "- Do NOT mention this summarization request or that the context was compacted.",
  "- Output only the checkpoint text: do not call any tool or take any other action.",
  `- If the conversation already contains a ${SUMMARY_OPEN_TAG} block, it is a PRIOR checkpoint. Do not copy it forward verbatim: preserve still-true facts, drop stale ones, and merge newer information into a single consolidated summary under the same structure.`
].join("\n");
function splitCuratorConfig(config) {
  const curator = {};
  const basic = {};
  for (const [key, value] of Object.entries(config)) {
    if (key === "curatorProvider") {
      if (typeof value === "string" && value.trim() !== "") curator.curatorProvider = value;
    } else if (key === "curatorModel") {
      if (typeof value === "string" && value.trim() !== "") curator.curatorModel = value;
    } else if (key === "curatorMaxTokens") {
      if (typeof value === "number" && Number.isInteger(value) && value > 0) curator.curatorMaxTokens = value;
    } else {
      basic[key] = value;
    }
  }
  return { curator, basic };
}

// src/compaction/curator.ts
var name = "dsh-tavern/compaction";
var BASIC_CONFIG_KEYS = /* @__PURE__ */ new Set([
  "thresholdRatio",
  "retainRatio",
  "retainTokens",
  "summarizationProvider",
  "summarizationModel",
  "maxTokens",
  "compactionRetries",
  "maxOverflowRetries",
  "modelPolicies",
  "auto"
]);
var { BasicCompactionEngine } = await importHostPackage("@deepseek-ai/dsh-compaction-basic");
var { BlockAssembler, createUserMessage, contentHasImage, LlmError } = await importHostPackage("@deepseek-ai/dsh-llm");
var TavernCompactionCurator = class extends BasicCompactionEngine {
  static inject = ["llm", "tokenMeter", "sessions"];
  curator;
  constructor(ctx, config = {}) {
    super(ctx, basicConfigOnly(config));
    this.curator = readCuratorOptions(config);
  }
  /** 非 AgentTavern 会话透传宿主默认摘要；Tavern 会话改用 RP 检查点。 */
  async summarize(input, agent, signal) {
    if (!await isAgentTavernSession(agent.session.id)) return super.summarize(input, agent, signal);
    return summarizeStoryCheckpoint(this.ctx, this.config, this.curator, input, agent, signal);
  }
};
var curator_default = TavernCompactionCurator;
async function importHostPackage(name2) {
  const anchor = process.argv[1];
  if (typeof anchor === "string" && anchor !== "") {
    try {
      const hostRequire = createRequire2(anchor);
      return await import(pathToFileURL(hostRequire.resolve(name2)).href);
    } catch {
    }
  }
  return await import(name2);
}
function basicConfigOnly(config) {
  return Object.fromEntries(Object.entries(config).filter(([key]) => BASIC_CONFIG_KEYS.has(key)));
}
function readCuratorOptions(config) {
  const { curator } = splitCuratorConfig(config);
  return curator;
}
function resolveCuratorTarget(config, curator, agent) {
  if (curator.curatorProvider !== void 0 && curator.curatorModel !== void 0) {
    return { provider: curator.curatorProvider, model: curator.curatorModel };
  }
  const routed = agent.session.requestHeader()?.config;
  if (typeof routed?.provider === "string" && routed.provider.length > 0 && typeof routed.model === "string" && routed.model.length > 0) {
    return { provider: routed.provider, model: routed.model };
  }
  const options = agent.options;
  if (typeof options?.provider === "string" && options.provider.length > 0 && typeof options.model === "string" && options.model.length > 0) {
    return { provider: options.provider, model: options.model };
  }
  return void 0;
}
async function summarizeStoryCheckpoint(ctx, config, curator, input, agent, signal) {
  const target = resolveCuratorTarget(config, curator, agent);
  if (target === void 0) {
    throw new Error("no provider/model available for AgentTavern story compaction: route one request or set curatorProvider and curatorModel");
  }
  const assembler = new BlockAssembler();
  const messages = [
    ...input.messages,
    createUserMessage({
      content: [{ type: "text", text: RP_COMPACTION_INSTRUCTION }],
      source: { kind: "plugin", plugin: "dsh-tavern" }
    })
  ];
  const maxTokens = curator.curatorMaxTokens ?? (typeof config.maxTokens === "number" ? config.maxTokens : 8192);
  const options = {
    provider: target.provider,
    model: target.model,
    messages,
    ...input.system === void 0 ? {} : { system: input.system },
    ...input.tools === void 0 ? {} : { tools: [...input.tools] },
    maxTokens,
    sessionId: agent.session.id,
    purpose: "compaction",
    ...signal === void 0 ? {} : { signal }
  };
  for await (const chunk of ctx.llm.stream(options)) assembler.push(chunk);
  const failure = finishError(assembler.finish);
  if (failure !== void 0) throw failure;
  const rawOutput = assembler.blocks();
  const summary = summaryText(rawOutput);
  if (!summary.some((block) => block.text.trim().length > 0)) {
    throw new Error("AgentTavern story compaction produced no text summary content");
  }
  return {
    summary,
    rawOutput,
    llmStreamCall: true,
    provider: options.provider,
    model: options.model,
    maxTokens,
    ...assembler.usage === void 0 ? {} : { usage: assembler.usage }
  };
}
function summaryText(blocks) {
  if (contentHasImage(blocks)) {
    throw new LlmError("compaction summary cannot contain image output", "UNSUPPORTED_CONTENT");
  }
  return blocks.filter((block) => block.type === "text" && typeof block.text === "string");
}
function finishError(finish) {
  switch (finish.kind) {
    case "error":
    case "aborted": {
      const failure = finish.failure ?? { message: "summarization failed", code: "UNKNOWN" };
      const error = new Error(failure.message);
      error.code = failure.code;
      return error;
    }
    case "max-tokens":
      return new Error("summarization truncated at the token cap (incomplete checkpoint)");
    default:
      return void 0;
  }
}
var tavernStorePromise;
function tavernStore() {
  return tavernStorePromise ??= TavernStore.open(dshHomePath("tavern"));
}
function dshHomePath(...segments) {
  const configured = process.env.DSH_HOME?.trim();
  return join2(resolve(configured || join2(homedir(), ".dsh")), ...segments);
}
async function isAgentTavernSession(sessionId) {
  try {
    const binding = (await (await tavernStore()).getState()).sessionBindings[sessionId];
    return binding !== void 0 && binding.architecture === "agent-tavern" && binding.group !== true;
  } catch {
    return false;
  }
}
export {
  TavernCompactionCurator,
  curator_default as default,
  name
};
