import { build } from 'esbuild'
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const versionPath = resolve(root, 'packages/plugin/version.json')
const version = JSON.parse(readFileSync(resolve(root, 'packages/plugin/package.json'), 'utf8')).version
const commit = resolveCommit()

await build({
  entryPoints: [resolve(root, 'packages/plugin/src/index.ts')],
  outfile: resolve(root, 'packages/plugin/index.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  packages: 'bundle',
  banner: { js: '// Generated by scripts/build-plugin.mjs. Do not edit.\n' },
})

await build({
  entryPoints: [resolve(root, 'packages/plugin/src/agent-tavern/agent.ts')],
  outfile: resolve(root, 'packages/plugin/agent.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  packages: 'bundle',
  banner: { js: '// Generated by scripts/build-plugin.mjs. Do not edit.\n' },
})

// compaction curator 的宿主 peer 依赖（@deepseek-ai/dsh-compaction-basic、
// dsh-llm）不做静态 import，运行时从宿主安装锚动态解析（见 curator.ts），
// 因此这里不需要 external；esbuild 只打包本仓库源码。
await build({
  entryPoints: [resolve(root, 'packages/plugin/src/compaction/curator.ts')],
  outfile: resolve(root, 'packages/plugin/compaction.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  packages: 'bundle',
  banner: { js: '// Generated by scripts/build-plugin.mjs. Do not edit.\n' },
})

writeFileSync(versionPath, `${JSON.stringify({ version, commit }, null, 2)}\n`, 'utf8')
console.log(`built packages/plugin/index.mjs, agent.mjs, compaction.mjs and version.json (v${version} ${commit})`)

function resolveCommit() {
  const configured = [
    process.env.DSH_TAVERN_COMMIT,
    process.env.GITHUB_SHA,
    process.env.CI_COMMIT_SHA,
    process.env.BUILD_SOURCEVERSION,
  ].map(normalizeCommit).find(Boolean)
  if (configured) return configured

  try {
    return normalizeCommit(execFileSync('git', ['rev-parse', '--short=7', 'HEAD'], {
      cwd: root,
      encoding: 'utf8',
      windowsHide: true,
    })) ?? 'unknown'
  } catch {
    return 'unknown'
  }
}

function normalizeCommit(value) {
  const commit = value?.trim()
  return commit && /^[0-9a-f]{7,40}$/i.test(commit)
    ? commit.slice(0, 7).toLowerCase()
    : undefined
}
