import { build } from 'esbuild'
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const versionPath = resolve(root, 'packages/plugin/version.json')
const version = JSON.parse(readFileSync(resolve(root, 'packages/plugin/package.json'), 'utf8')).version
const commit = resolveCommit()

await build({
  entryPoints: [resolve(root, 'packages/plugin/src/index.ts')],
  outfile: resolve(root, 'packages/plugin/index.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  packages: 'bundle',
  banner: { js: '// Generated by scripts/build-plugin.mjs. Do not edit.\n' },
})

await build({
  entryPoints: [resolve(root, 'packages/plugin/src/agent-tavern/agent.ts')],
  outfile: resolve(root, 'packages/plugin/agent.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  packages: 'bundle',
  banner: { js: '// Generated by scripts/build-plugin.mjs. Do not edit.\n' },
})

// compaction curator 的宿主 peer 依赖（@deepseek-ai/dsh-compaction-basic、
// dsh-llm）不做静态 import，运行时从宿主安装锚动态解析（见 curator.ts 与
// @dsh-tavern/bind 的 host-package），
// 因此这里不需要 external；esbuild 只打包本仓库源码。
await build({
  entryPoints: [resolve(root, 'packages/plugin/src/compaction/curator.ts')],
  outfile: resolve(root, 'packages/plugin/compaction.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  packages: 'bundle',
  banner: { js: '// Generated by scripts/build-plugin.mjs. Do not edit.\n' },
})

// client half 拼接：@dsh-tavern/bind 的 client 探测模块（uiWorkspace →
// workspaces 双面回退 + 形状轨迹）打成 IIFE，替换 client/main.js factory 顶部的
// __DSH_BIND_CLIENT_SLOT__ 标记，生成产物 client/index.js。client half 走宿主
// ModuleLoader 的 factory(require)，无法相对 import 本地模块，共享代码只能
// 构建期内联。
const bindClientBundle = await build({
  entryPoints: [resolve(root, 'packages/bind/src/client/host-probe.ts')],
  bundle: true,
  format: 'iife',
  globalName: 'DshBindClient',
  platform: 'browser',
  target: 'es2022',
  sourcemap: false,
  write: false,
})
const bindClientIife = indentCode(bindClientBundle.outputFiles[0].text.trimEnd(), 4)
const clientMainSource = readFileSync(resolve(root, 'packages/plugin/client/main.js'), 'utf8')
const bindSlot = '    // __DSH_BIND_CLIENT_SLOT__'
if (!clientMainSource.includes(bindSlot)) {
  throw new Error('client/main.js is missing the __DSH_BIND_CLIENT_SLOT__ injection marker')
}
const clientBundleSource = clientMainSource.replace(
  bindSlot,
  `${bindClientIife}\n    const clientShapeTrace = DshBindClient.createClientShapeTrace()\n    window.__DSH_TAVERN_BIND__ = clientShapeTrace`,
)
writeFileSync(resolve(root, 'packages/plugin/client/index.js'), clientBundleSource, 'utf8')

writeFileSync(versionPath, `${JSON.stringify({ version, commit }, null, 2)}\n`, 'utf8')
console.log(`built packages/plugin/index.mjs, agent.mjs, compaction.mjs, client/index.js and version.json (v${version} ${commit})`)

function indentCode(code, width) {
  const pad = ' '.repeat(width)
  return code.split('\n').map((line) => (line === '' ? line : pad + line)).join('\n')
}

function resolveCommit() {
  const configured = [
    process.env.DSH_TAVERN_COMMIT,
    process.env.GITHUB_SHA,
    process.env.CI_COMMIT_SHA,
    process.env.BUILD_SOURCEVERSION,
  ].map(normalizeCommit).find(Boolean)
  if (configured) return configured

  try {
    return normalizeCommit(execFileSync('git', ['rev-parse', '--short=7', 'HEAD'], {
      cwd: root,
      encoding: 'utf8',
      windowsHide: true,
    })) ?? 'unknown'
  } catch {
    return 'unknown'
  }
}

function normalizeCommit(value) {
  const commit = value?.trim()
  return commit && /^[0-9a-f]{7,40}$/i.test(commit)
    ? commit.slice(0, 7).toLowerCase()
    : undefined
}
