import { build } from 'esbuild'
import { readFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const version = JSON.parse(readFileSync(resolve(root, 'packages/plugin/package.json'), 'utf8')).version
let commit = 'unknown'
try {
  commit = execSync('git rev-parse --short HEAD', { cwd: root, windowsHide: true }).toString().trim()
} catch {
  // not a git checkout (e.g. installed from a tarball): keep the placeholder
}
await build({
  entryPoints: [resolve(root, 'packages/plugin/src/index.ts')],
  outfile: resolve(root, 'packages/plugin/index.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  packages: 'bundle',
  define: {
    __TAVERN_VERSION__: JSON.stringify(version),
    __TAVERN_COMMIT__: JSON.stringify(commit),
  },
  banner: { js: '// Generated by scripts/build-plugin.mjs. Do not edit.\n' },
})
console.log(`built packages/plugin/index.mjs (v${version} ${commit})`)
